// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputUser struct {
	Firstname            string  `json:"firstname"`
	Lastname             *string `json:"lastname,omitempty"`
	Password             string  `json:"password"`
	PasswordConfirmation string  `json:"password_confirmation"`
	Email                string  `json:"email"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type TokenOutput struct {
	Success      *bool   `json:"success,omitempty"`
	Message      *string `json:"message,omitempty"`
	AccessToken  string  `json:"access_token"`
	RefreshToken string  `json:"refresh_token"`
}

type UpdateAccountInput struct {
	Firstname *string `json:"firstname,omitempty"`
	Lastname  *string `json:"lastname,omitempty"`
	Password  *string `json:"password,omitempty"`
	Email     *string `json:"email,omitempty"`
}

type UserOutput struct {
	Firstname string  `json:"firstname"`
	Lastname  *string `json:"lastname,omitempty"`
	Email     string  `json:"email"`
}
